<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Richard L Halter (private) -->
<xs:schema xmlns="http://www.nrf-arts.org/IXRetail/namespace/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.nrf-arts.org/IXRetail/namespace/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="IXREnumerationExtensionV1.1.0.xsd"/>
	<xs:simpleType name="ResponseFormatTypeCode">
		<xs:union memberTypes="ResponseFormatTypeCodeEnumeration TypeCodeExtension"/>
	</xs:simpleType>
	<xs:simpleType name="ResponseFormatTypeCodeEnumeration">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="Picture"/>
			<xs:enumeration value="Map"/>
			<xs:enumeration value="Hyperlink"/>
			<xs:enumeration value="List"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
