<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Richard L Halter (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="UnitOfMeasureCodeEnumerationV1.2.0.xsd"/>
	<xs:complexType name="StartEndTimeType">
		<xs:sequence>
			<xs:element name="StartDate" type="xs:date" minOccurs="0"/>
			<xs:element name="StartTime" type="xs:time" minOccurs="0"/>
			<xs:element name="EndTime" type="xs:time" minOccurs="0"/>
			<xs:element name="Duration" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:duration">
							<xs:attribute name="UnitOfMeasureCode" type="UnitOfMeasureCodeCommonData" use="optional" default="Days"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="EndDate" type="xs:date" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
