<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	Version 1.1.0
	- Added Call Center and Web Site to list
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="IXREnumerationExtensionV1.1.0.xsd"/>
	<!--
		Enumerated type for Time Zones Type attribute
	-->
	<xs:simpleType name="TimeZonesTypeCode">
		<xs:union memberTypes="TimeZonesTypeCodeEnumeration TypeCodeExtension"/>
	</xs:simpleType>
	<xs:simpleType name="TimeZonesTypeCodeEnumeration">
		<xs:restriction base="xs:NMTOKEN">
		<xs:enumeration value="ACDT"><xs:annotation><xs:documentation>Australian Central Daylight Time	UTC+10:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ACST"><xs:annotation><xs:documentation>Australian Central Standard Time	UTC+09:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ACT"><xs:annotation><xs:documentation>ASEAN Common Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ADT"><xs:annotation><xs:documentation>Atlantic Daylight Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AEDT"><xs:annotation><xs:documentation>Australian Eastern Daylight Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AEST"><xs:annotation><xs:documentation>Australian Eastern Standard Time	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AFT"><xs:annotation><xs:documentation>Afghanistan Time	UTC+04:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AKDT"><xs:annotation><xs:documentation>Alaska Daylight Time	UTC−08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AKST"><xs:annotation><xs:documentation>Alaska Standard Time	UTC−09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AMST"><xs:annotation><xs:documentation>Amazon Summer Time (Brazil)[1]	UTC−03 or Armenia Summer Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AMT"><xs:annotation><xs:documentation>Amazon Time (Brazil)[2]	UTC−04 or Armenia Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ART"><xs:annotation><xs:documentation>Argentina Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AST"><xs:annotation><xs:documentation>Arabia Standard Time	UTC+03 or Atlantic Standard Time	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AWDT"><xs:annotation><xs:documentation>Australian Western Daylight Time	UTC+09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AWST"><xs:annotation><xs:documentation>Australian Western Standard Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AZOST"><xs:annotation><xs:documentation>Azores Standard Time	UTC−01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="AZT"><xs:annotation><xs:documentation>Azerbaijan Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BDT"><xs:annotation><xs:documentation>Brunei Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BIOT"><xs:annotation><xs:documentation>British Indian Ocean Time	UTC+06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BIT"><xs:annotation><xs:documentation>Baker Island Time	UTC−12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BOT"><xs:annotation><xs:documentation>Bolivia Time	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BRT"><xs:annotation><xs:documentation>Brasilia Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BST"><xs:annotation><xs:documentation>Bangladesh Standard Time	UTC+06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BST"><xs:annotation><xs:documentation>British Summer Time (British Standard Time from Feb 1968 to Oct 1971)	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="BTT"><xs:annotation><xs:documentation>Bhutan Time	UTC+06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CAT"><xs:annotation><xs:documentation>Central Africa Time	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CCT"><xs:annotation><xs:documentation>Cocos Islands Time	UTC+06:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CDT"><xs:annotation><xs:documentation>Central Daylight Time (North America)	UTC−05 or Cuba Daylight Time[3]	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CEDT"><xs:annotation><xs:documentation>Central European Daylight Time	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CEST"><xs:annotation><xs:documentation>Central European Summer Time (Cf. HAEC)	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CET"><xs:annotation><xs:documentation>Central European Time	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CHADT"><xs:annotation><xs:documentation>Chatham Daylight Time	UTC+13:45</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CHAST"><xs:annotation><xs:documentation>Chatham Standard Time	UTC+12:45</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CHOT"><xs:annotation><xs:documentation>Choibalsan	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CHST"><xs:annotation><xs:documentation>Chamorro Standard Time	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CHUT"><xs:annotation><xs:documentation>Chuuk Time	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CIST"><xs:annotation><xs:documentation>Clipperton Island Standard Time	UTC−08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CIT"><xs:annotation><xs:documentation>Central Indonesia Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CKT"><xs:annotation><xs:documentation>Cook Island Time	UTC−10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CLST"><xs:annotation><xs:documentation>Chile Summer Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CLT"><xs:annotation><xs:documentation>Chile Standard Time	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="COST"><xs:annotation><xs:documentation>Colombia Summer Time	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="COT"><xs:annotation><xs:documentation>Colombia Time	UTC−05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CST"><xs:annotation><xs:documentation>Central Standard Time (North America)	UTC−06 or China Standard Time	UTC+08 or Central Standard Time (Australia)	UTC+09:30 or	Central Summer Time (Australia)	UTC+10:30 or Cuba Standard Time	UTC−05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CT"><xs:annotation><xs:documentation>China time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CVT"><xs:annotation><xs:documentation>Cape Verde Time	UTC−01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CWST"><xs:annotation><xs:documentation>Central Western Standard Time (Australia) unofficial	UTC+08:45</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="CXT"><xs:annotation><xs:documentation>Christmas Island Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="DAVT"><xs:annotation><xs:documentation>Davis Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="DDUT"><xs:annotation><xs:documentation>Dumont d'Urville Time	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="DFT"><xs:annotation><xs:documentation>AIX specific equivalent of Central European Time[4]	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EASST"><xs:annotation><xs:documentation>Easter Island Standard Summer Time	UTC−05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EAST"><xs:annotation><xs:documentation>Easter Island Standard Time	UTC−06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EAT"><xs:annotation><xs:documentation>East Africa Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ECT"><xs:annotation><xs:documentation>Eastern Caribbean Time (does not recognise DST)	UTC−04 or Ecuador Time	UTC−05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EDT"><xs:annotation><xs:documentation>Eastern Daylight Time (North America)	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EEDT"><xs:annotation><xs:documentation>Eastern European Daylight Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EEST"><xs:annotation><xs:documentation>Eastern European Summer Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EET"><xs:annotation><xs:documentation>Eastern European Time	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EGST"><xs:annotation><xs:documentation>Eastern Greenland Summer Time	UTC+00</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EGT"><xs:annotation><xs:documentation>Eastern Greenland Time	UTC−01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EIT"><xs:annotation><xs:documentation>Eastern Indonesian Time	UTC+09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="EST"><xs:annotation><xs:documentation>Eastern Standard Time (North America)	UTC−05 or Eastern Standard Time (Australia)	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="FET"><xs:annotation><xs:documentation>Further-eastern European Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="FJT"><xs:annotation><xs:documentation>Fiji Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="FKST"><xs:annotation><xs:documentation>Falkland Islands Standard Time	UTC−03 or Falkland Islands Summer Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="FKT"><xs:annotation><xs:documentation>Falkland Islands Time	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="FNT"><xs:annotation><xs:documentation>Fernando de Noronha Time	UTC−02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GALT"><xs:annotation><xs:documentation>Galapagos Time	UTC−06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GAMT"><xs:annotation><xs:documentation>Gambier Islands	UTC−09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GET"><xs:annotation><xs:documentation>Georgia Standard Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GFT"><xs:annotation><xs:documentation>French Guiana Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GILT"><xs:annotation><xs:documentation>Gilbert Island Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GIT"><xs:annotation><xs:documentation>Gambier Island Time	UTC−09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GMT"><xs:annotation><xs:documentation>Greenwich Mean Time	UTC</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GST"><xs:annotation><xs:documentation>South Georgia and the South Sandwich Islands	UTC−02 or Gulf Standard Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="GYT"><xs:annotation><xs:documentation>Guyana Time	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HADT"><xs:annotation><xs:documentation>Hawaii-Aleutian Daylight Time	UTC−09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HAEC"><xs:annotation><xs:documentation>Heure Avancée d'Europe Centrale francised name for CEST	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HAST"><xs:annotation><xs:documentation>Hawaii-Aleutian Standard Time	UTC−10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HKT"><xs:annotation><xs:documentation>Hong Kong Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HMT"><xs:annotation><xs:documentation>Heard and McDonald Islands Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HOVT"><xs:annotation><xs:documentation>Khovd Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="HST"><xs:annotation><xs:documentation>Hawaii Standard Time	UTC−10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ICT"><xs:annotation><xs:documentation>Indochina Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="IDT"><xs:annotation><xs:documentation>Israel Daylight Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="IOT"><xs:annotation><xs:documentation>Indian Ocean Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="IRDT"><xs:annotation><xs:documentation>Iran Daylight Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="IRKT"><xs:annotation><xs:documentation>Irkutsk Time	UTC+09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="IRST"><xs:annotation><xs:documentation>Iran Standard Time	UTC+03:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="IST"><xs:annotation><xs:documentation>Indian Standard Time	UTC+05:30 or Irish Standard Time[5]	UTC+01 or Israel Standard Time	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="JST"><xs:annotation><xs:documentation>Japan Standard Time	UTC+09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="KGT"><xs:annotation><xs:documentation>Kyrgyzstan time	UTC+06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="KOST"><xs:annotation><xs:documentation>Kosrae Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="KRAT"><xs:annotation><xs:documentation>Krasnoyarsk Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="KST"><xs:annotation><xs:documentation>Korea Standard Time	UTC+09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="LHST"><xs:annotation><xs:documentation>Lord Howe Standard Time	UTC+10:30 or Lord Howe Summer Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="LINT"><xs:annotation><xs:documentation>Line Islands Time	UTC+14</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MAGT"><xs:annotation><xs:documentation>Magadan Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MART"><xs:annotation><xs:documentation>Marquesas Islands Time	UTC−09:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MAWT"><xs:annotation><xs:documentation>Mawson Station Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MDT"><xs:annotation><xs:documentation>Mountain Daylight Time (North America)	UTC−06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MEST"><xs:annotation><xs:documentation>Middle European Saving Time Same zone as CEST	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MET"><xs:annotation><xs:documentation>Middle European Time Same zone as CET	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MHT"><xs:annotation><xs:documentation>Marshall Islands	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MIST"><xs:annotation><xs:documentation>Macquarie Island Station Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MIT"><xs:annotation><xs:documentation>Marquesas Islands Time	UTC−09:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MMT"><xs:annotation><xs:documentation>Myanmar Time	UTC+06:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MSK"><xs:annotation><xs:documentation>Moscow Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MST"><xs:annotation><xs:documentation>Malaysia Standard Time	UTC+08 or Mountain Standard Time (North America)	UTC−07 or Myanmar Standard Time	UTC+06:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MUT"><xs:annotation><xs:documentation>Mauritius Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MVT"><xs:annotation><xs:documentation>Maldives Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="MYT"><xs:annotation><xs:documentation>Malaysia Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NCT"><xs:annotation><xs:documentation>New Caledonia Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NDT"><xs:annotation><xs:documentation>Newfoundland Daylight Time	UTC−02:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NFT"><xs:annotation><xs:documentation>Norfolk Time	UTC+11:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NPT"><xs:annotation><xs:documentation>Nepal Time	UTC+05:45</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NST"><xs:annotation><xs:documentation>Newfoundland Standard Time	UTC−03:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NT"><xs:annotation><xs:documentation>Newfoundland Time	UTC−03:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NUT"><xs:annotation><xs:documentation>Niue Time	UTC−11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NZDT"><xs:annotation><xs:documentation>New Zealand Daylight Time	UTC+13</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="NZST"><xs:annotation><xs:documentation>New Zealand Standard Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="OMST"><xs:annotation><xs:documentation>Omsk Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ORAT"><xs:annotation><xs:documentation>Oral Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PDT"><xs:annotation><xs:documentation>Pacific Daylight Time (North America)	UTC−07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PET"><xs:annotation><xs:documentation>Peru Time	UTC−05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PETT"><xs:annotation><xs:documentation>Kamchatka Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PGT"><xs:annotation><xs:documentation>Papua New Guinea Time	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PHOT"><xs:annotation><xs:documentation>Phoenix Island Time	UTC+13</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PHT"><xs:annotation><xs:documentation>Philippine Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PKT"><xs:annotation><xs:documentation>Pakistan Standard Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PMDT"><xs:annotation><xs:documentation>Saint Pierre and Miquelon Daylight time	UTC−02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PMST"><xs:annotation><xs:documentation>Saint Pierre and Miquelon Standard Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PONT"><xs:annotation><xs:documentation>Pohnpei Standard Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PST"><xs:annotation><xs:documentation>Pacific Standard Time (North America)	UTC−08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PYST"><xs:annotation><xs:documentation>Paraguay Summer Time (South America)[6]	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="PYT"><xs:annotation><xs:documentation>Paraguay Time (South America)[7]	UTC−04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="RET"><xs:annotation><xs:documentation>Réunion Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ROTT"><xs:annotation><xs:documentation>Rothera Research Station Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SAKT"><xs:annotation><xs:documentation>Sakhalin Island time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SAMT"><xs:annotation><xs:documentation>Samara Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SAST"><xs:annotation><xs:documentation>South African Standard Time	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SBT"><xs:annotation><xs:documentation>Solomon Islands Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SCT"><xs:annotation><xs:documentation>Seychelles Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SGT"><xs:annotation><xs:documentation>Singapore Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SLST"><xs:annotation><xs:documentation>Sri Lanka Time	UTC+05:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SRT"><xs:annotation><xs:documentation>Suriname Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SST"><xs:annotation><xs:documentation>Samoa Standard Time	UTC−11 or Singapore Standard Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="SYOT"><xs:annotation><xs:documentation>Showa Station Time	UTC+03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TAHT"><xs:annotation><xs:documentation>Tahiti Time	UTC−10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TFT"><xs:annotation><xs:documentation>Indian/Kerguelen	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="THA"><xs:annotation><xs:documentation>Thailand Standard Time	UTC+07</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TJT"><xs:annotation><xs:documentation>Tajikistan Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TKT"><xs:annotation><xs:documentation>Tokelau Time	UTC+13</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TLT"><xs:annotation><xs:documentation>Timor Leste Time	UTC+09</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TMT"><xs:annotation><xs:documentation>Turkmenistan Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TOT"><xs:annotation><xs:documentation>Tonga Time	UTC+13</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="TVT"><xs:annotation><xs:documentation>Tuvalu Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="UCT"><xs:annotation><xs:documentation>Coordinated Universal Time	UTC</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="ULAT"><xs:annotation><xs:documentation>Ulaanbaatar Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="UTC"><xs:annotation><xs:documentation>Coordinated Universal Time	UTC</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="UYST"><xs:annotation><xs:documentation>Uruguay Summer Time	UTC−02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="UYT"><xs:annotation><xs:documentation>Uruguay Standard Time	UTC−03</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="UZT"><xs:annotation><xs:documentation>Uzbekistan Time	UTC+05</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="VET"><xs:annotation><xs:documentation>Venezuelan Standard Time	UTC−04:30</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="VLAT"><xs:annotation><xs:documentation>Vladivostok Time	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="VOLT"><xs:annotation><xs:documentation>Volgograd Time	UTC+04</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="VOST"><xs:annotation><xs:documentation>Vostok Station Time	UTC+06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="VUT"><xs:annotation><xs:documentation>Vanuatu Time	UTC+11</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WAKT"><xs:annotation><xs:documentation>Wake Island Time	UTC+12</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WAST"><xs:annotation><xs:documentation>West Africa Summer Time	UTC+02</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WAT"><xs:annotation><xs:documentation>West Africa Time	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WEDT"><xs:annotation><xs:documentation>Western European Daylight Time	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WEST"><xs:annotation><xs:documentation>Western European Summer Time	UTC+01</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WET"><xs:annotation><xs:documentation>Western European Time	UTC</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="WST"><xs:annotation><xs:documentation>Western Standard Time	UTC+08</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="YAKT"><xs:annotation><xs:documentation>Yakutsk Time	UTC+10</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="YEKT"><xs:annotation><xs:documentation>Yekaterinburg Time	UTC+06</xs:documentation></xs:annotation></xs:enumeration>
		<xs:enumeration value="Z"><xs:annotation><xs:documentation>Zulu Time (Coordinated Universal Time)	UTC</xs:documentation></xs:annotation></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

