<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Richard L Halter (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="EntryMethodTypeCodeEnumerationV1.2.0.xsd"/>
	<xs:include schemaLocation="MonetaryAmountCommonDataV1.2.0.xsd"/>
	<xs:include schemaLocation="UnitOfMeasureCodeEnumerationV1.3.0.xsd"/>
	<xs:complexType name="UnitPriceCommonData">
		<xs:simpleContent>
			<xs:extension base="MonetaryAmountCommonData">
				<xs:attribute name="Quantity" type="xs:decimal" use="optional" default="1"/>
				<xs:attribute name="UnitOfMeasureCode" type="UnitOfMeasureCodeCommonData" use="optional" default="EA"/>
				<xs:attribute name="EntryMethod" type="EntryMethodTypeCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>
