<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="IXREnumerationExtensionV1.1.0.xsd"/>
	<!--
		Enumerated type for Workstation Types 
	-->
	<xs:simpleType name="WorkstationIDTypeCode">
		<xs:union memberTypes="WorkstationIDTypeCodeEnumeration TypeCodeExtension"/>
	</xs:simpleType>
	<xs:simpleType name="WorkstationIDTypeCodeEnumeration">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="ATM"/>
			<xs:enumeration value="CallCenterStation"/>
			<xs:enumeration value="Kiosk"/>
			<xs:enumeration value="Network"/>
			<xs:enumeration value="POI">
				<xs:annotation>
					<xs:documentation>Point of Interaction (payment subsystem)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="POS"/>
			<xs:enumeration value="URI"/>
			<xs:enumeration value="Website"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
