// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbtsp

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAlert struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	RuleID      pgtype.UUID        `json:"rule_id"`
	Severity    string             `json:"severity"`
	Status      string             `json:"status"`
	SourceTable string             `json:"source_table"`
	SourceID    pgtype.UUID        `json:"source_id"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	LocationID  pgtype.UUID        `json:"location_id"`
	ImpactCents int64              `json:"impact_cents"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AppAlertHistory struct {
	ID         pgtype.UUID        `json:"id"`
	AlertID    pgtype.UUID        `json:"alert_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Note       pgtype.Text        `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppAuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppBullApiCredential struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	ApiKeyEncrypted string             `json:"api_key_encrypted"`
	EndpointUrl     string             `json:"endpoint_url"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
}

type AppBullEventLog struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppBullMerchantConfig struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	PollIntervalS int32              `json:"poll_interval_s"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppBullPollWatermark struct {
	ID           pgtype.UUID        `json:"id"`
	MerchantID   pgtype.UUID        `json:"merchant_id"`
	EndpointName string             `json:"endpoint_name"`
	LastModified pgtype.Timestamptz `json:"last_modified"`
	LastRunAt    pgtype.Timestamptz `json:"last_run_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AppCustomer struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	SquareCustomerID string             `json:"square_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	ModifiedBy       pgtype.UUID        `json:"modified_by"`
	DbStatus         string             `json:"db_status"`
	DbEffectiveFrom  pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo    pgtype.Timestamptz `json:"db_effective_to"`
}

type AppDetectionRule struct {
	ID               pgtype.UUID        `json:"id"`
	RuleID           string             `json:"rule_id"`
	Category         string             `json:"category"`
	Severity         string             `json:"severity"`
	DefaultThreshold pgtype.Numeric     `json:"default_threshold"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AppEmployee struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	SquareEmployeeID string             `json:"square_employee_id"`
	EmployeeName     string             `json:"employee_name"`
	Email            pgtype.Text        `json:"email"`
	RiskScore        pgtype.Numeric     `json:"risk_score"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	ModifiedBy       pgtype.UUID        `json:"modified_by"`
	DbStatus         string             `json:"db_status"`
	DbEffectiveFrom  pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo    pgtype.Timestamptz `json:"db_effective_to"`
}

type AppEmployeeLocationAssignment struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	LocationID pgtype.UUID        `json:"location_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

type AppExternalIdentity struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	SourceCode string             `json:"source_code"`
	ExternalID string             `json:"external_id"`
	IsPrimary  bool               `json:"is_primary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

type AppFoxCase struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	AlertID     pgtype.UUID        `json:"alert_id"`
	Status      string             `json:"status"`
	CaseType    string             `json:"case_type"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	OpenedBy    pgtype.UUID        `json:"opened_by"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AppFoxEvidence struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	CaseID        pgtype.UUID        `json:"case_id"`
	RecordType    string             `json:"record_type"`
	RecordPayload []byte             `json:"record_payload"`
	ChainHash     string             `json:"chain_hash"`
	UploadedBy    pgtype.Text        `json:"uploaded_by"`
	FilePath      pgtype.Text        `json:"file_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppFoxEvidenceAccessLog struct {
	ID         pgtype.UUID        `json:"id"`
	EvidenceID pgtype.UUID        `json:"evidence_id"`
	AccessedBy string             `json:"accessed_by"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
}

type AppFoxSubject struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	CaseID     pgtype.UUID        `json:"case_id"`
	Name       string             `json:"name"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	EntityType pgtype.Text        `json:"entity_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AppFoxTimeline struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	CaseID      pgtype.UUID        `json:"case_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	EventType   string             `json:"event_type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppHawkOauthToken struct {
	ID                    pgtype.UUID        `json:"id"`
	MerchantID            pgtype.UUID        `json:"merchant_id"`
	AccessTokenEncrypted  string             `json:"access_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text        `json:"refresh_token_encrypted"`
	TokenType             string             `json:"token_type"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Scopes                pgtype.Text        `json:"scopes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	ModifiedBy            pgtype.UUID        `json:"modified_by"`
}

type AppIngestionLog struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	EventID     string             `json:"event_id"`
	SourceCode  pgtype.Text        `json:"source_code"`
	ChainHash   string             `json:"chain_hash"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	Stage       string             `json:"stage"`
}

type AppInterestSignup struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppLocation struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	SquareLocationID string             `json:"square_location_id"`
	LocationName     string             `json:"location_name"`
	AddressLine1     pgtype.Text        `json:"address_line1"`
	AddressLine2     pgtype.Text        `json:"address_line2"`
	City             pgtype.Text        `json:"city"`
	State            pgtype.Text        `json:"state"`
	PostalCode       pgtype.Text        `json:"postal_code"`
	Coordinates      []byte             `json:"coordinates"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	ModifiedBy       pgtype.UUID        `json:"modified_by"`
	DbStatus         string             `json:"db_status"`
	DbEffectiveFrom  pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo    pgtype.Timestamptz `json:"db_effective_to"`
}

type AppLocationHierarchy struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	Name            string             `json:"name"`
	Level           int16              `json:"level"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	DbStatus        string             `json:"db_status"`
	DbEffectiveFrom pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo   pgtype.Timestamptz `json:"db_effective_to"`
}

type AppMerchant struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	SourceMerchantID string             `json:"source_merchant_id"`
	MerchantName     string             `json:"merchant_name"`
	Currency         string             `json:"currency"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AppMerchantRuleConfig struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	RuleID          pgtype.UUID        `json:"rule_id"`
	IsEnabled       bool               `json:"is_enabled"`
	CustomThreshold pgtype.Numeric     `json:"custom_threshold"`
	NotifyEnabled   bool               `json:"notify_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
}

type AppMerchantSetting struct {
	ID                     pgtype.UUID        `json:"id"`
	MerchantID             pgtype.UUID        `json:"merchant_id"`
	Timezone               string             `json:"timezone"`
	Language               string             `json:"language"`
	DateFormat             pgtype.Text        `json:"date_format"`
	CalendarType           string             `json:"calendar_type"`
	FiscalYearStartMonth   pgtype.Int2        `json:"fiscal_year_start_month"`
	FiscalWeekStartDay     pgtype.Int2        `json:"fiscal_week_start_day"`
	FiscalPattern          pgtype.Text        `json:"fiscal_pattern"`
	NotifEmailEnabled      bool               `json:"notif_email_enabled"`
	NotifSmsEnabled        bool               `json:"notif_sms_enabled"`
	NotifInAppEnabled      bool               `json:"notif_in_app_enabled"`
	NotifQuietHoursStart   pgtype.Int2        `json:"notif_quiet_hours_start"`
	NotifQuietHoursEnd     pgtype.Int2        `json:"notif_quiet_hours_end"`
	NotifSeverityThreshold pgtype.Text        `json:"notif_severity_threshold"`
	NotifDailyLimit        pgtype.Int4        `json:"notif_daily_limit"`
	NotifPhone             pgtype.Text        `json:"notif_phone"`
	Theme                  pgtype.Text        `json:"theme"`
	ShowEmployeeNames      bool               `json:"show_employee_names"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type AppMerchantSource struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	SourceCode     string             `json:"source_code"`
	RaasNamespace  pgtype.Text        `json:"raas_namespace"`
	Status         string             `json:"status"`
	MetadataJson   []byte             `json:"metadata_json"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ModifiedBy     pgtype.UUID        `json:"modified_by"`
}

type AppMerkleBatch struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	BatchID    string             `json:"batch_id"`
	RootHash   string             `json:"root_hash"`
	EventCount int32              `json:"event_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppOrganization struct {
	ID                pgtype.UUID        `json:"id"`
	OrgName           string             `json:"org_name"`
	BillingEmail      pgtype.Text        `json:"billing_email"`
	SubscriptionTier  string             `json:"subscription_tier"`
	BillingProvider   pgtype.Text        `json:"billing_provider"`
	BillingExternalID pgtype.Text        `json:"billing_external_id"`
	BillingStatus     pgtype.Text        `json:"billing_status"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	ModifiedBy        pgtype.UUID        `json:"modified_by"`
	DbStatus          string             `json:"db_status"`
	DbEffectiveFrom   pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo     pgtype.Timestamptz `json:"db_effective_to"`
}

type AppProduct struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	SquareItemID    string             `json:"square_item_id"`
	ProductName     string             `json:"product_name"`
	Sku             pgtype.Text        `json:"sku"`
	Upc             pgtype.Text        `json:"upc"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	DbStatus        string             `json:"db_status"`
	DbEffectiveFrom pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo   pgtype.Timestamptz `json:"db_effective_to"`
}

type AppRole struct {
	ID          pgtype.UUID        `json:"id"`
	RoleName    string             `json:"role_name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceSystem struct {
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	Category    string             `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AppUser struct {
	ID              pgtype.UUID        `json:"id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	DisplayName     pgtype.Text        `json:"display_name"`
	IsActive        bool               `json:"is_active"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ModifiedBy      pgtype.UUID        `json:"modified_by"`
	DbStatus        string             `json:"db_status"`
	DbEffectiveFrom pgtype.Timestamptz `json:"db_effective_from"`
	DbEffectiveTo   pgtype.Timestamptz `json:"db_effective_to"`
}

type AppUserEmployeeLink struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

type AppUserRole struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ModifiedBy pgtype.UUID        `json:"modified_by"`
}

type SalesCashDrawerEvent struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	ShiftID     pgtype.UUID        `json:"shift_id"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	EventType   string             `json:"event_type"`
	AmountCents pgtype.Int8        `json:"amount_cents"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SalesCashDrawerShift struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	EmployeeID       pgtype.UUID        `json:"employee_id"`
	ExternalID       string             `json:"external_id"`
	OpenedAt         pgtype.Timestamptz `json:"opened_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	ExpectedCents    pgtype.Int8        `json:"expected_cents"`
	ActualCents      pgtype.Int8        `json:"actual_cents"`
	DiscrepancyCents pgtype.Int8        `json:"discrepancy_cents"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SalesLineItem struct {
	ID             pgtype.UUID        `json:"id"`
	MerchantID     pgtype.UUID        `json:"merchant_id"`
	TransactionID  pgtype.UUID        `json:"transaction_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	ExternalID     pgtype.Text        `json:"external_id"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	UnitPriceCents int64              `json:"unit_price_cents"`
	TotalCents     int64              `json:"total_cents"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SalesLineItemDiscount struct {
	ID            pgtype.UUID        `json:"id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	LineItemID    pgtype.UUID        `json:"line_item_id"`
	DiscountName  pgtype.Text        `json:"discount_name"`
	DiscountCents int64              `json:"discount_cents"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SalesRefundLink struct {
	ID                    pgtype.UUID        `json:"id"`
	MerchantID            pgtype.UUID        `json:"merchant_id"`
	RefundTransactionID   pgtype.UUID        `json:"refund_transaction_id"`
	OriginalTransactionID pgtype.UUID        `json:"original_transaction_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type SalesTransaction struct {
	ID                   pgtype.UUID        `json:"id"`
	MerchantID           pgtype.UUID        `json:"merchant_id"`
	ExternalID           string             `json:"external_id"`
	LocationID           pgtype.UUID        `json:"location_id"`
	EmployeeID           pgtype.UUID        `json:"employee_id"`
	CustomerID           pgtype.UUID        `json:"customer_id"`
	ArtsBusinessDate     pgtype.Date        `json:"arts_business_date"`
	ArtsWorkstationID    pgtype.Text        `json:"arts_workstation_id"`
	TransactionType      string             `json:"transaction_type"`
	TotalCents           int64              `json:"total_cents"`
	SubtotalCents        int64              `json:"subtotal_cents"`
	TaxCents             int64              `json:"tax_cents"`
	TipCents             int64              `json:"tip_cents"`
	DiscountCents        int64              `json:"discount_cents"`
	TenderType           pgtype.Text        `json:"tender_type"`
	CardFingerprint      pgtype.Text        `json:"card_fingerprint"`
	CardLast4            pgtype.Text        `json:"card_last4"`
	CardBin              pgtype.Text        `json:"card_bin"`
	CardExpMonth         pgtype.Int2        `json:"card_exp_month"`
	CardExpYear          pgtype.Int2        `json:"card_exp_year"`
	StatementDescription pgtype.Text        `json:"statement_description"`
	Payload              []byte             `json:"payload"`
	SourceCode           pgtype.Text        `json:"source_code"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
