// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tsp.sql

package dbtsp

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTSPLastSequence = `-- name: GetTSPLastSequence :one
SELECT id, merchant_id, source_code, sequence_id, event_id,
       received_at, gap_detected, expected_prev_seq
  FROM protocol.tsp_sequence_log
 WHERE merchant_id = $1 AND source_code = $2
 ORDER BY received_at DESC
 LIMIT 1
`

type GetTSPLastSequenceParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	SourceCode string      `json:"source_code"`
}

func (q *Queries) GetTSPLastSequence(ctx context.Context, arg *GetTSPLastSequenceParams) (*ProtocolTspSequenceLog, error) {
	row := q.db.QueryRow(ctx, getTSPLastSequence, arg.MerchantID, arg.SourceCode)
	var i ProtocolTspSequenceLog
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SourceCode,
		&i.SequenceID,
		&i.EventID,
		&i.ReceivedAt,
		&i.GapDetected,
		&i.ExpectedPrevSeq,
	)
	return &i, err
}

const insertTSPSequenceLog = `-- name: InsertTSPSequenceLog :one

INSERT INTO protocol.tsp_sequence_log (
    merchant_id, source_code, sequence_id, event_id,
    gap_detected, expected_prev_seq
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, source_code, sequence_id, event_id,
          received_at, gap_detected, expected_prev_seq
`

type InsertTSPSequenceLogParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	SourceCode      string      `json:"source_code"`
	SequenceID      string      `json:"sequence_id"`
	EventID         pgtype.UUID `json:"event_id"`
	GapDetected     bool        `json:"gap_detected"`
	ExpectedPrevSeq pgtype.Text `json:"expected_prev_seq"`
}

// internal/db/sqlc/tsp.sql
//
// TSP sequence-log queries. Table: protocol.tsp_sequence_log
// (GRO-764 Phase A.2 + Wave C schema migration to canonical deploy/schema/).
//
// The old queries (app.ingestion_log, sales.transactions) are archived
// alongside the pre-Wave-A migrations in deploy/migrations/_archived/.
func (q *Queries) InsertTSPSequenceLog(ctx context.Context, arg *InsertTSPSequenceLogParams) (*ProtocolTspSequenceLog, error) {
	row := q.db.QueryRow(ctx, insertTSPSequenceLog,
		arg.MerchantID,
		arg.SourceCode,
		arg.SequenceID,
		arg.EventID,
		arg.GapDetected,
		arg.ExpectedPrevSeq,
	)
	var i ProtocolTspSequenceLog
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SourceCode,
		&i.SequenceID,
		&i.EventID,
		&i.ReceivedAt,
		&i.GapDetected,
		&i.ExpectedPrevSeq,
	)
	return &i, err
}

const listTSPGaps = `-- name: ListTSPGaps :many
SELECT id, merchant_id, source_code, sequence_id, event_id,
       received_at, gap_detected, expected_prev_seq
  FROM protocol.tsp_sequence_log
 WHERE merchant_id = $1 AND source_code = $2 AND gap_detected = true
 ORDER BY received_at DESC
 LIMIT $3
`

type ListTSPGapsParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	SourceCode string      `json:"source_code"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListTSPGaps(ctx context.Context, arg *ListTSPGapsParams) ([]*ProtocolTspSequenceLog, error) {
	rows, err := q.db.Query(ctx, listTSPGaps, arg.MerchantID, arg.SourceCode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProtocolTspSequenceLog
	for rows.Next() {
		var i ProtocolTspSequenceLog
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.SourceCode,
			&i.SequenceID,
			&i.EventID,
			&i.ReceivedAt,
			&i.GapDetected,
			&i.ExpectedPrevSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
