// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tsp.sql

package dbtsp

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIngestionLogByEventID = `-- name: GetIngestionLogByEventID :one
SELECT id, merchant_id, event_id, source_code, chain_hash, received_at, processed_at, stage
FROM app.ingestion_log
WHERE event_id = $1
`

func (q *Queries) GetIngestionLogByEventID(ctx context.Context, eventID string) (*AppIngestionLog, error) {
	row := q.db.QueryRow(ctx, getIngestionLogByEventID, eventID)
	var i AppIngestionLog
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EventID,
		&i.SourceCode,
		&i.ChainHash,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Stage,
	)
	return &i, err
}

const insertIngestionLog = `-- name: InsertIngestionLog :one

INSERT INTO app.ingestion_log (merchant_id, event_id, source_code, chain_hash, stage)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, merchant_id, event_id, source_code, chain_hash, received_at, stage
`

type InsertIngestionLogParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	EventID    string      `json:"event_id"`
	SourceCode pgtype.Text `json:"source_code"`
	ChainHash  string      `json:"chain_hash"`
	Stage      string      `json:"stage"`
}

type InsertIngestionLogRow struct {
	ID         pgtype.UUID        `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	EventID    string             `json:"event_id"`
	SourceCode pgtype.Text        `json:"source_code"`
	ChainHash  string             `json:"chain_hash"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	Stage      string             `json:"stage"`
}

// internal/db/sqlc/tsp.sql
func (q *Queries) InsertIngestionLog(ctx context.Context, arg *InsertIngestionLogParams) (*InsertIngestionLogRow, error) {
	row := q.db.QueryRow(ctx, insertIngestionLog,
		arg.MerchantID,
		arg.EventID,
		arg.SourceCode,
		arg.ChainHash,
		arg.Stage,
	)
	var i InsertIngestionLogRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EventID,
		&i.SourceCode,
		&i.ChainHash,
		&i.ReceivedAt,
		&i.Stage,
	)
	return &i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO sales.transactions (
    merchant_id, external_id, location_id, employee_id,
    arts_business_date, transaction_type, total_cents,
    subtotal_cents, tax_cents, tender_type, source_code
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, merchant_id, external_id, arts_business_date, total_cents, created_at
`

type InsertTransactionParams struct {
	MerchantID       pgtype.UUID `json:"merchant_id"`
	ExternalID       string      `json:"external_id"`
	LocationID       pgtype.UUID `json:"location_id"`
	EmployeeID       pgtype.UUID `json:"employee_id"`
	ArtsBusinessDate pgtype.Date `json:"arts_business_date"`
	TransactionType  string      `json:"transaction_type"`
	TotalCents       int64       `json:"total_cents"`
	SubtotalCents    int64       `json:"subtotal_cents"`
	TaxCents         int64       `json:"tax_cents"`
	TenderType       pgtype.Text `json:"tender_type"`
	SourceCode       pgtype.Text `json:"source_code"`
}

type InsertTransactionRow struct {
	ID               pgtype.UUID        `json:"id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	ExternalID       string             `json:"external_id"`
	ArtsBusinessDate pgtype.Date        `json:"arts_business_date"`
	TotalCents       int64              `json:"total_cents"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg *InsertTransactionParams) (*InsertTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.MerchantID,
		arg.ExternalID,
		arg.LocationID,
		arg.EmployeeID,
		arg.ArtsBusinessDate,
		arg.TransactionType,
		arg.TotalCents,
		arg.SubtotalCents,
		arg.TaxCents,
		arg.TenderType,
		arg.SourceCode,
	)
	var i InsertTransactionRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalID,
		&i.ArtsBusinessDate,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return &i, err
}
