// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package dbtransaction

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, tenant_id, transaction_number, transaction_type,
       parent_transaction_id, location_id, pos_terminal_id,
       cashier_employee_id, customer_id, loyalty_membership_id,
       party_id, business_date::text, started_at, ended_at,
       status, ticket_number, item_count,
       subtotal::numeric, tax_total::numeric,
       discount_total::numeric, grand_total::numeric,
       currency, channel, is_training_mode, is_offline,
       void_reason, created_at, updated_at
  FROM t.transactions
 WHERE tenant_id = $1 AND id = $2
`

type GetTransactionByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetTransactionByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	TransactionNumber   string             `json:"transaction_number"`
	TransactionType     string             `json:"transaction_type"`
	ParentTransactionID pgtype.UUID        `json:"parent_transaction_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	PosTerminalID       pgtype.Text        `json:"pos_terminal_id"`
	CashierEmployeeID   pgtype.UUID        `json:"cashier_employee_id"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	LoyaltyMembershipID pgtype.UUID        `json:"loyalty_membership_id"`
	PartyID             pgtype.UUID        `json:"party_id"`
	BusinessDate        string             `json:"business_date"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	Status              string             `json:"status"`
	TicketNumber        pgtype.Int4        `json:"ticket_number"`
	ItemCount           int32              `json:"item_count"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	TaxTotal            pgtype.Numeric     `json:"tax_total"`
	DiscountTotal       pgtype.Numeric     `json:"discount_total"`
	GrandTotal          pgtype.Numeric     `json:"grand_total"`
	Currency            string             `json:"currency"`
	Channel             string             `json:"channel"`
	IsTrainingMode      bool               `json:"is_training_mode"`
	IsOffline           bool               `json:"is_offline"`
	VoidReason          pgtype.Text        `json:"void_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg *GetTransactionByIDParams) (*GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.TenantID, arg.ID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TransactionNumber,
		&i.TransactionType,
		&i.ParentTransactionID,
		&i.LocationID,
		&i.PosTerminalID,
		&i.CashierEmployeeID,
		&i.CustomerID,
		&i.LoyaltyMembershipID,
		&i.PartyID,
		&i.BusinessDate,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TicketNumber,
		&i.ItemCount,
		&i.Subtotal,
		&i.TaxTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.Channel,
		&i.IsTrainingMode,
		&i.IsOffline,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTransactionByReceiptNumber = `-- name: GetTransactionByReceiptNumber :one
SELECT id, tenant_id, transaction_number, transaction_type,
       parent_transaction_id, location_id, pos_terminal_id,
       cashier_employee_id, customer_id, loyalty_membership_id,
       party_id, business_date::text, started_at, ended_at,
       status, ticket_number, item_count,
       subtotal::numeric, tax_total::numeric,
       discount_total::numeric, grand_total::numeric,
       currency, channel, is_training_mode, is_offline,
       void_reason, created_at, updated_at
  FROM t.transactions
 WHERE tenant_id = $1
   AND location_id = $2
   AND business_date = $3::date
   AND transaction_number = $4
`

type GetTransactionByReceiptNumberParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	LocationID        pgtype.UUID `json:"location_id"`
	Column3           pgtype.Date `json:"column_3"`
	TransactionNumber string      `json:"transaction_number"`
}

type GetTransactionByReceiptNumberRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	TransactionNumber   string             `json:"transaction_number"`
	TransactionType     string             `json:"transaction_type"`
	ParentTransactionID pgtype.UUID        `json:"parent_transaction_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	PosTerminalID       pgtype.Text        `json:"pos_terminal_id"`
	CashierEmployeeID   pgtype.UUID        `json:"cashier_employee_id"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	LoyaltyMembershipID pgtype.UUID        `json:"loyalty_membership_id"`
	PartyID             pgtype.UUID        `json:"party_id"`
	BusinessDate        string             `json:"business_date"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	Status              string             `json:"status"`
	TicketNumber        pgtype.Int4        `json:"ticket_number"`
	ItemCount           int32              `json:"item_count"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	TaxTotal            pgtype.Numeric     `json:"tax_total"`
	DiscountTotal       pgtype.Numeric     `json:"discount_total"`
	GrandTotal          pgtype.Numeric     `json:"grand_total"`
	Currency            string             `json:"currency"`
	Channel             string             `json:"channel"`
	IsTrainingMode      bool               `json:"is_training_mode"`
	IsOffline           bool               `json:"is_offline"`
	VoidReason          pgtype.Text        `json:"void_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTransactionByReceiptNumber(ctx context.Context, arg *GetTransactionByReceiptNumberParams) (*GetTransactionByReceiptNumberRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByReceiptNumber,
		arg.TenantID,
		arg.LocationID,
		arg.Column3,
		arg.TransactionNumber,
	)
	var i GetTransactionByReceiptNumberRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TransactionNumber,
		&i.TransactionType,
		&i.ParentTransactionID,
		&i.LocationID,
		&i.PosTerminalID,
		&i.CashierEmployeeID,
		&i.CustomerID,
		&i.LoyaltyMembershipID,
		&i.PartyID,
		&i.BusinessDate,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TicketNumber,
		&i.ItemCount,
		&i.Subtotal,
		&i.TaxTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.Channel,
		&i.IsTrainingMode,
		&i.IsOffline,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertDiscount = `-- name: InsertDiscount :exec
INSERT INTO t.transaction_discounts (
    tenant_id, transaction_id, discount_sequence, scope,
    discount_type, amount, reason_code, attributes
) VALUES (
    $1, $2, $3, 'transaction', $4, $5::numeric, $6,
    COALESCE($7::jsonb, '{}'::jsonb)
)
`

type InsertDiscountParams struct {
	TenantID         pgtype.UUID    `json:"tenant_id"`
	TransactionID    pgtype.UUID    `json:"transaction_id"`
	DiscountSequence int32          `json:"discount_sequence"`
	DiscountType     string         `json:"discount_type"`
	Column5          pgtype.Numeric `json:"column_5"`
	ReasonCode       pgtype.Text    `json:"reason_code"`
	Column7          []byte         `json:"column_7"`
}

func (q *Queries) InsertDiscount(ctx context.Context, arg *InsertDiscountParams) error {
	_, err := q.db.Exec(ctx, insertDiscount,
		arg.TenantID,
		arg.TransactionID,
		arg.DiscountSequence,
		arg.DiscountType,
		arg.Column5,
		arg.ReasonCode,
		arg.Column7,
	)
	return err
}

const insertLineItem = `-- name: InsertLineItem :exec
INSERT INTO t.transaction_line_items (
    tenant_id, transaction_id, line_number, item_id, description,
    quantity, unit_of_measure, unit_price, unit_tax, attributes
) VALUES (
    $1, $2, $3, $4, $5,
    $6::numeric, 'EA', $7::numeric, $8::numeric,
    COALESCE($9::jsonb, '{}'::jsonb)
)
`

type InsertLineItemParams struct {
	TenantID      pgtype.UUID    `json:"tenant_id"`
	TransactionID pgtype.UUID    `json:"transaction_id"`
	LineNumber    int32          `json:"line_number"`
	ItemID        pgtype.UUID    `json:"item_id"`
	Description   string         `json:"description"`
	Column6       pgtype.Numeric `json:"column_6"`
	Column7       pgtype.Numeric `json:"column_7"`
	Column8       pgtype.Numeric `json:"column_8"`
	Column9       []byte         `json:"column_9"`
}

func (q *Queries) InsertLineItem(ctx context.Context, arg *InsertLineItemParams) error {
	_, err := q.db.Exec(ctx, insertLineItem,
		arg.TenantID,
		arg.TransactionID,
		arg.LineNumber,
		arg.ItemID,
		arg.Description,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	return err
}

const insertTender = `-- name: InsertTender :exec
INSERT INTO t.transaction_tenders (
    tenant_id, transaction_id, tender_sequence, tender_type_id,
    amount, currency, processor_reference, attributes
) VALUES (
    $1, $2, $3, $4, $5::numeric, $6, $7,
    COALESCE($8::jsonb, '{}'::jsonb)
)
`

type InsertTenderParams struct {
	TenantID           pgtype.UUID    `json:"tenant_id"`
	TransactionID      pgtype.UUID    `json:"transaction_id"`
	TenderSequence     int32          `json:"tender_sequence"`
	TenderTypeID       pgtype.UUID    `json:"tender_type_id"`
	Column5            pgtype.Numeric `json:"column_5"`
	Currency           string         `json:"currency"`
	ProcessorReference pgtype.Text    `json:"processor_reference"`
	Column8            []byte         `json:"column_8"`
}

func (q *Queries) InsertTender(ctx context.Context, arg *InsertTenderParams) error {
	_, err := q.db.Exec(ctx, insertTender,
		arg.TenantID,
		arg.TransactionID,
		arg.TenderSequence,
		arg.TenderTypeID,
		arg.Column5,
		arg.Currency,
		arg.ProcessorReference,
		arg.Column8,
	)
	return err
}

const insertTransactionHeader = `-- name: InsertTransactionHeader :one

INSERT INTO t.transactions (
    tenant_id, transaction_number, transaction_type, parent_transaction_id,
    location_id, pos_terminal_id, cashier_employee_id, customer_id,
    loyalty_membership_id, business_date, started_at, ended_at, status,
    ticket_number, item_count, subtotal, tax_total, discount_total,
    grand_total, currency, channel, pos_software_version,
    is_training_mode, is_offline, attributes, external_ids
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10::date, $11, $12, $13,
    $14, $15, $16::numeric, $17::numeric, $18::numeric, $19::numeric,
    $20, $21, $22, $23, $24,
    COALESCE($25::jsonb, '{}'::jsonb),
    COALESCE($26::jsonb, '{}'::jsonb)
)
RETURNING id, tenant_id, transaction_number, transaction_type,
          parent_transaction_id, location_id, pos_terminal_id,
          cashier_employee_id, customer_id, loyalty_membership_id,
          party_id, business_date::text, started_at, ended_at,
          status, ticket_number, item_count,
          subtotal::numeric, tax_total::numeric,
          discount_total::numeric, grand_total::numeric,
          currency, channel, is_training_mode, is_offline,
          void_reason, created_at, updated_at
`

type InsertTransactionHeaderParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	TransactionNumber   string             `json:"transaction_number"`
	TransactionType     string             `json:"transaction_type"`
	ParentTransactionID pgtype.UUID        `json:"parent_transaction_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	PosTerminalID       pgtype.Text        `json:"pos_terminal_id"`
	CashierEmployeeID   pgtype.UUID        `json:"cashier_employee_id"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	LoyaltyMembershipID pgtype.UUID        `json:"loyalty_membership_id"`
	Column10            pgtype.Date        `json:"column_10"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	Status              string             `json:"status"`
	TicketNumber        pgtype.Int4        `json:"ticket_number"`
	ItemCount           int32              `json:"item_count"`
	Column16            pgtype.Numeric     `json:"column_16"`
	Column17            pgtype.Numeric     `json:"column_17"`
	Column18            pgtype.Numeric     `json:"column_18"`
	Column19            pgtype.Numeric     `json:"column_19"`
	Currency            string             `json:"currency"`
	Channel             string             `json:"channel"`
	PosSoftwareVersion  pgtype.Text        `json:"pos_software_version"`
	IsTrainingMode      bool               `json:"is_training_mode"`
	IsOffline           bool               `json:"is_offline"`
	Column25            []byte             `json:"column_25"`
	Column26            []byte             `json:"column_26"`
}

type InsertTransactionHeaderRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	TransactionNumber   string             `json:"transaction_number"`
	TransactionType     string             `json:"transaction_type"`
	ParentTransactionID pgtype.UUID        `json:"parent_transaction_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	PosTerminalID       pgtype.Text        `json:"pos_terminal_id"`
	CashierEmployeeID   pgtype.UUID        `json:"cashier_employee_id"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	LoyaltyMembershipID pgtype.UUID        `json:"loyalty_membership_id"`
	PartyID             pgtype.UUID        `json:"party_id"`
	BusinessDate        string             `json:"business_date"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	Status              string             `json:"status"`
	TicketNumber        pgtype.Int4        `json:"ticket_number"`
	ItemCount           int32              `json:"item_count"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	TaxTotal            pgtype.Numeric     `json:"tax_total"`
	DiscountTotal       pgtype.Numeric     `json:"discount_total"`
	GrandTotal          pgtype.Numeric     `json:"grand_total"`
	Currency            string             `json:"currency"`
	Channel             string             `json:"channel"`
	IsTrainingMode      bool               `json:"is_training_mode"`
	IsOffline           bool               `json:"is_offline"`
	VoidReason          pgtype.Text        `json:"void_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// internal/db/sqlc/transaction.sql
//
// Named queries for the t.transactions canonical write path. The store
// in internal/transaction/store.go orchestrates these within a pgx.Tx
// for the multi-statement Create/Void/Return operations.
//
// GENERATED columns (line_total, extended_price, extended_tax, margin)
// are excluded from INSERT statements — Postgres computes them. They
// appear in RETURNING / SELECT clauses.
//
// Spec: GRO-764 Phase B.1 + GRO-765 Phase D carry-forward B.3.
func (q *Queries) InsertTransactionHeader(ctx context.Context, arg *InsertTransactionHeaderParams) (*InsertTransactionHeaderRow, error) {
	row := q.db.QueryRow(ctx, insertTransactionHeader,
		arg.TenantID,
		arg.TransactionNumber,
		arg.TransactionType,
		arg.ParentTransactionID,
		arg.LocationID,
		arg.PosTerminalID,
		arg.CashierEmployeeID,
		arg.CustomerID,
		arg.LoyaltyMembershipID,
		arg.Column10,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.TicketNumber,
		arg.ItemCount,
		arg.Column16,
		arg.Column17,
		arg.Column18,
		arg.Column19,
		arg.Currency,
		arg.Channel,
		arg.PosSoftwareVersion,
		arg.IsTrainingMode,
		arg.IsOffline,
		arg.Column25,
		arg.Column26,
	)
	var i InsertTransactionHeaderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TransactionNumber,
		&i.TransactionType,
		&i.ParentTransactionID,
		&i.LocationID,
		&i.PosTerminalID,
		&i.CashierEmployeeID,
		&i.CustomerID,
		&i.LoyaltyMembershipID,
		&i.PartyID,
		&i.BusinessDate,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TicketNumber,
		&i.ItemCount,
		&i.Subtotal,
		&i.TaxTotal,
		&i.DiscountTotal,
		&i.GrandTotal,
		&i.Currency,
		&i.Channel,
		&i.IsTrainingMode,
		&i.IsOffline,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listDiscountsByTransaction = `-- name: ListDiscountsByTransaction :many
SELECT id, transaction_id, discount_type,
       amount::numeric, reason_code, created_at
  FROM t.transaction_discounts
 WHERE transaction_id = $1
 ORDER BY discount_sequence
`

type ListDiscountsByTransactionRow struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	DiscountType  string             `json:"discount_type"`
	Amount        pgtype.Numeric     `json:"amount"`
	ReasonCode    pgtype.Text        `json:"reason_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDiscountsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]*ListDiscountsByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listDiscountsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDiscountsByTransactionRow
	for rows.Next() {
		var i ListDiscountsByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.DiscountType,
			&i.Amount,
			&i.ReasonCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsByTransaction = `-- name: ListLineItemsByTransaction :many
SELECT id, transaction_id, line_number, item_id, description,
       quantity::numeric, unit_price::numeric,
       line_total::numeric, extended_tax::numeric, created_at
  FROM t.transaction_line_items
 WHERE transaction_id = $1
 ORDER BY line_number
`

type ListLineItemsByTransactionRow struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	LineNumber    int32              `json:"line_number"`
	ItemID        pgtype.UUID        `json:"item_id"`
	Description   string             `json:"description"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	UnitPrice     pgtype.Numeric     `json:"unit_price"`
	LineTotal     pgtype.Numeric     `json:"line_total"`
	ExtendedTax   pgtype.Numeric     `json:"extended_tax"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListLineItemsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]*ListLineItemsByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listLineItemsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListLineItemsByTransactionRow
	for rows.Next() {
		var i ListLineItemsByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.LineNumber,
			&i.ItemID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.ExtendedTax,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTendersByTransaction = `-- name: ListTendersByTransaction :many
SELECT id, transaction_id, tender_type_id,
       amount::numeric, currency, processor_reference, created_at
  FROM t.transaction_tenders
 WHERE transaction_id = $1
 ORDER BY tender_sequence
`

type ListTendersByTransactionRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TransactionID      pgtype.UUID        `json:"transaction_id"`
	TenderTypeID       pgtype.UUID        `json:"tender_type_id"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	ProcessorReference pgtype.Text        `json:"processor_reference"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTendersByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]*ListTendersByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listTendersByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTendersByTransactionRow
	for rows.Next() {
		var i ListTendersByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.TenderTypeID,
			&i.Amount,
			&i.Currency,
			&i.ProcessorReference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, tenant_id, transaction_number, transaction_type,
       parent_transaction_id, location_id, pos_terminal_id,
       cashier_employee_id, customer_id, loyalty_membership_id,
       party_id, business_date::text, started_at, ended_at,
       status, ticket_number, item_count,
       subtotal::numeric, tax_total::numeric,
       discount_total::numeric, grand_total::numeric,
       currency, channel, is_training_mode, is_offline,
       void_reason, created_at, updated_at
  FROM t.transactions
 WHERE tenant_id = $1
 ORDER BY started_at DESC
 LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListTransactionsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	TransactionNumber   string             `json:"transaction_number"`
	TransactionType     string             `json:"transaction_type"`
	ParentTransactionID pgtype.UUID        `json:"parent_transaction_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	PosTerminalID       pgtype.Text        `json:"pos_terminal_id"`
	CashierEmployeeID   pgtype.UUID        `json:"cashier_employee_id"`
	CustomerID          pgtype.UUID        `json:"customer_id"`
	LoyaltyMembershipID pgtype.UUID        `json:"loyalty_membership_id"`
	PartyID             pgtype.UUID        `json:"party_id"`
	BusinessDate        string             `json:"business_date"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	Status              string             `json:"status"`
	TicketNumber        pgtype.Int4        `json:"ticket_number"`
	ItemCount           int32              `json:"item_count"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	TaxTotal            pgtype.Numeric     `json:"tax_total"`
	DiscountTotal       pgtype.Numeric     `json:"discount_total"`
	GrandTotal          pgtype.Numeric     `json:"grand_total"`
	Currency            string             `json:"currency"`
	Channel             string             `json:"channel"`
	IsTrainingMode      bool               `json:"is_training_mode"`
	IsOffline           bool               `json:"is_offline"`
	VoidReason          pgtype.Text        `json:"void_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg *ListTransactionsParams) ([]*ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionNumber,
			&i.TransactionType,
			&i.ParentTransactionID,
			&i.LocationID,
			&i.PosTerminalID,
			&i.CashierEmployeeID,
			&i.CustomerID,
			&i.LoyaltyMembershipID,
			&i.PartyID,
			&i.BusinessDate,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TicketNumber,
			&i.ItemCount,
			&i.Subtotal,
			&i.TaxTotal,
			&i.DiscountTotal,
			&i.GrandTotal,
			&i.Currency,
			&i.Channel,
			&i.IsTrainingMode,
			&i.IsOffline,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionVoided = `-- name: UpdateTransactionVoided :exec
UPDATE t.transactions
   SET status = 'voided', void_reason = $3, updated_at = now()
 WHERE tenant_id = $1 AND id = $2
`

type UpdateTransactionVoidedParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ID         pgtype.UUID `json:"id"`
	VoidReason pgtype.Text `json:"void_reason"`
}

func (q *Queries) UpdateTransactionVoided(ctx context.Context, arg *UpdateTransactionVoidedParams) error {
	_, err := q.db.Exec(ctx, updateTransactionVoided, arg.TenantID, arg.ID, arg.VoidReason)
	return err
}
