// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbidentity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO app.merchants (organization_id, source_merchant_id, merchant_name, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, source_merchant_id, merchant_name, currency, is_active,
          created_at, updated_at
`

type CreateMerchantParams struct {
	OrganizationID   pgtype.UUID `json:"organization_id"`
	SourceMerchantID string      `json:"source_merchant_id"`
	MerchantName     string      `json:"merchant_name"`
	Currency         string      `json:"currency"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg *CreateMerchantParams) (*AppMerchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.OrganizationID,
		arg.SourceMerchantID,
		arg.MerchantName,
		arg.Currency,
	)
	var i AppMerchant
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SourceMerchantID,
		&i.MerchantName,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO app.organizations (org_name, subscription_tier)
VALUES ($1, $2)
RETURNING id, org_name, subscription_tier, is_active, created_at, updated_at
`

type CreateOrganizationParams struct {
	OrgName          string `json:"org_name"`
	SubscriptionTier string `json:"subscription_tier"`
}

type CreateOrganizationRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgName          string             `json:"org_name"`
	SubscriptionTier string             `json:"subscription_tier"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg *CreateOrganizationParams) (*CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.OrgName, arg.SubscriptionTier)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.OrgName,
		&i.SubscriptionTier,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app.users (merchant_id, username, email, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, username, email, display_name, is_active, created_at, updated_at
`

type CreateUserParams struct {
	MerchantID  pgtype.UUID `json:"merchant_id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.MerchantID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one

SELECT id, organization_id, source_merchant_id, merchant_name, currency, is_active,
       created_at, updated_at
FROM app.merchants
WHERE id = $1
`

// internal/db/sqlc/identity.sql
func (q *Queries) GetMerchantByID(ctx context.Context, id pgtype.UUID) (*AppMerchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i AppMerchant
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SourceMerchantID,
		&i.MerchantName,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantBySourceID = `-- name: GetMerchantBySourceID :one
SELECT id, organization_id, source_merchant_id, merchant_name, currency, is_active,
       created_at, updated_at
FROM app.merchants
WHERE source_merchant_id = $1
`

func (q *Queries) GetMerchantBySourceID(ctx context.Context, sourceMerchantID string) (*AppMerchant, error) {
	row := q.db.QueryRow(ctx, getMerchantBySourceID, sourceMerchantID)
	var i AppMerchant
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SourceMerchantID,
		&i.MerchantName,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, merchant_id, username, email, display_name, is_active, last_login_at,
       created_at, updated_at
FROM app.users
WHERE merchant_id = $1 AND email = $2 AND db_status = 'active'
`

type GetUserByEmailParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Email      string      `json:"email"`
}

type GetUserByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg *GetUserByEmailParams) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.MerchantID, arg.Email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, merchant_id, username, email, display_name, is_active, last_login_at,
       created_at, updated_at
FROM app.users
WHERE id = $1 AND db_status = 'active'
`

type GetUserByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.role_name
FROM app.user_roles ur
JOIN app.roles r ON r.id = ur.role_id
WHERE ur.user_id = $1 AND ur.merchant_id = $2
`

type GetUserRolesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) GetUserRoles(ctx context.Context, arg *GetUserRolesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, arg.UserID, arg.MerchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE app.users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
