# seacove — Roof Planes
# Generated by ARC AI Draftsman.
# Boundaries are pre-expanded by overhang in the Python generator.

H = SeacoveHelpers
model = Sketchup.active_model
ents = model.active_entities

model.start_operation("seacove Roof", true)

# Roof plane: Living Wing Roof (flat, slope=0.02, overhang=3.5ft)
roof_grp = H.tagged_group(ents, model, "Roof")
roof_grp.name = "Living_Wing_Roof"
roof_pts = [
  H.pt(-2.944125, -1.892652, 8.833333333333334),
  H.pt(30.944125, -1.892652, 8.833333333333334),
  H.pt(30.944125, 19.892652, 8.833333333333334),
  H.pt(-2.944125, 19.892652, 8.833333333333334),
]
roof_face = roof_grp.entities.add_face(roof_pts)
if roof_face
  roof_face.reverse! if roof_face.normal.z < 0
  roof_face.pushpull(H.ft(0.4))  # 0.4ft roof thickness
end
# Roof plane: Bedroom Wing Roof (flat, slope=0.02, overhang=3.5ft)
roof_grp = H.tagged_group(ents, model, "Roof")
roof_grp.name = "Bedroom_Wing_Roof"
roof_pts = [
  H.pt(15.72223, -2.657398, 8.533333333333333),
  H.pt(44.27777, -2.657398, 8.533333333333333),
  H.pt(44.27777, 30.657398, 8.533333333333333),
  H.pt(15.72223, 30.657398, 8.533333333333333),
]
roof_face = roof_grp.entities.add_face(roof_pts)
if roof_face
  roof_face.reverse! if roof_face.normal.z < 0
  roof_face.pushpull(H.ft(0.4))  # 0.4ft roof thickness
end
# Roof plane: Addition Roof (flat, slope=0.02, overhang=3.5ft)
roof_grp = H.tagged_group(ents, model, "Roof")
roof_grp.name = "Addition_Roof"
roof_pts = [
  H.pt(1.946229, 26.289888, 8.3),
  H.pt(33.053771, 26.289888, 8.3),
  H.pt(33.053771, 43.710112, 8.3),
  H.pt(1.946229, 43.710112, 8.3),
]
roof_face = roof_grp.entities.add_face(roof_pts)
if roof_face
  roof_face.reverse! if roof_face.normal.z < 0
  roof_face.pushpull(H.ft(0.4))  # 0.4ft roof thickness
end
# Roof plane: Garage Roof (flat, slope=0.02, overhang=3.5ft)
roof_grp = H.tagged_group(ents, model, "Roof")
roof_grp.name = "Garage_Roof"
roof_pts = [
  H.pt(39.39847, -4.341377, 7.5),
  H.pt(64.60153, -4.341377, 7.5),
  H.pt(64.60153, 18.341377, 7.5),
  H.pt(39.39847, 18.341377, 7.5),
]
roof_face = roof_grp.entities.add_face(roof_pts)
if roof_face
  roof_face.reverse! if roof_face.normal.z < 0
  roof_face.pushpull(H.ft(0.4))  # 0.4ft roof thickness
end

model.commit_operation
puts "seacove roof complete."
