# seacove — Walls
# Generated by ARC AI Draftsman.
# 21 wall(s) across 1 floor(s).

H = SeacoveHelpers
model = Sketchup.active_model
ents = model.active_entities

model.start_operation("seacove Walls", true)

# ============================================================
# Floor: Ground Floor (z=0.0, plate=8.0ft)
# ============================================================

# Wall: wall_s_living (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_s_living"
H.make_wall(
  wall_grp,
  [0.0, 0.0],
  [28.0, 0.0],
  0.5,
  8.0,
  0.0
)

# Opening: door (3.0ft wide x 7.0ft tall, sill 0.0ft)
cutter = ents.add_group
H.make_box(
  cutter,
  14.0,
  -0.25,
  0.0 + 0.0,
  3.0,
  0.5,
  7.0
)
wall_grp.subtract(cutter)

# Wall: wall_s_bedrooms (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_s_bedrooms"
H.make_wall(
  wall_grp,
  [28.0, 0.0],
  [42.0, 0.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_n_living (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_n_living"
H.make_wall(
  wall_grp,
  [0.0, 18.0],
  [28.0, 18.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_n_bedrooms (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_n_bedrooms"
H.make_wall(
  wall_grp,
  [18.0, 28.0],
  [42.0, 28.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_west (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_west"
H.make_wall(
  wall_grp,
  [0.0, 0.0],
  [0.0, 18.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_east (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_east"
H.make_wall(
  wall_grp,
  [42.0, 0.0],
  [42.0, 28.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_connect (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_connect"
H.make_wall(
  wall_grp,
  [18.0, 0.0],
  [18.0, 18.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_hall (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_hall"
H.make_wall(
  wall_grp,
  [18.0, 14.0],
  [42.0, 14.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_br1_divider (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_br1_divider"
H.make_wall(
  wall_grp,
  [26.0, 14.0],
  [26.0, 28.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_br2_divider (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_br2_divider"
H.make_wall(
  wall_grp,
  [34.0, 14.0],
  [34.0, 28.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_kitchen (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_kitchen"
H.make_wall(
  wall_grp,
  [12.0, 10.0],
  [18.0, 10.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_bath_south (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_bath_south"
H.make_wall(
  wall_grp,
  [18.0, 6.0],
  [24.0, 6.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_bath_west (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_bath_west"
H.make_wall(
  wall_grp,
  [24.0, 0.0],
  [24.0, 14.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_add_north (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_add_north"
H.make_wall(
  wall_grp,
  [5.0, 42.0],
  [30.0, 42.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_add_west (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_add_west"
H.make_wall(
  wall_grp,
  [5.0, 28.0],
  [5.0, 42.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_add_east (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_add_east"
H.make_wall(
  wall_grp,
  [30.0, 28.0],
  [30.0, 42.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_add_divider (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_add_divider"
H.make_wall(
  wall_grp,
  [17.0, 28.0],
  [17.0, 42.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_add_bath (interior)
wall_grp = H.tagged_group(ents, model, "Walls/Interior")
wall_grp.name = "wall_add_bath"
H.make_wall(
  wall_grp,
  [12.0, 35.0],
  [17.0, 35.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_gar_south (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_gar_south"
H.make_wall(
  wall_grp,
  [42.0, -2.0],
  [62.0, -2.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_gar_north (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_gar_north"
H.make_wall(
  wall_grp,
  [42.0, 16.0],
  [62.0, 16.0],
  0.5,
  8.0,
  0.0
)

# Wall: wall_gar_east (exterior)
wall_grp = H.tagged_group(ents, model, "Walls/Exterior")
wall_grp.name = "wall_gar_east"
H.make_wall(
  wall_grp,
  [62.0, -2.0],
  [62.0, 16.0],
  0.5,
  8.0,
  0.0
)

model.commit_operation
puts "seacove walls complete."
