# seacove — Structural Posts and Beams
# Generated by ARC AI Draftsman.

H = SeacoveHelpers
model = Sketchup.active_model
ents = model.active_entities

model.start_operation("seacove Structure", true)

# ============================================================
# Posts
# ============================================================
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_1"
H.make_post(post_grp, 2.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_2"
H.make_post(post_grp, 8.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_3"
H.make_post(post_grp, 14.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_4"
H.make_post(post_grp, 20.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_5"
H.make_post(post_grp, 26.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_6"
H.make_post(post_grp, 2.0, 18.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_7"
H.make_post(post_grp, 8.0, 18.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_8"
H.make_post(post_grp, 14.0, 18.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_9"
H.make_post(post_grp, 20.0, 18.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_10"
H.make_post(post_grp, 26.0, 18.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_11"
H.make_post(post_grp, 42.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_12"
H.make_post(post_grp, 42.0, 14.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_13"
H.make_post(post_grp, 42.0, 28.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_14"
H.make_post(post_grp, 18.0, 28.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_15"
H.make_post(post_grp, 0.0, 0.0, 4.0, 8.0, 0.0)
post_grp = H.tagged_group(ents, model, "Structure/Posts")
post_grp.name = "post_16"
H.make_post(post_grp, 0.0, 18.0, 4.0, 8.0, 0.0)

# ============================================================
# Beams
# ============================================================
beam_grp = H.tagged_group(ents, model, "Structure/Beams")
beam_grp.name = "Ridge Beam - Living Wing"
H.make_beam(
  beam_grp,
  [-2.0, 9.0],
  [30.0, 9.0],
  4.0,
  10.0,
  8.0
)
beam_grp = H.tagged_group(ents, model, "Structure/Beams")
beam_grp.name = "Ridge Beam - Bedroom Wing"
H.make_beam(
  beam_grp,
  [18.0, 14.0],
  [44.0, 14.0],
  4.0,
  10.0,
  8.0
)

model.commit_operation
puts "seacove structure complete."
