from pathlib import Path
from graphs.state import PipelineState

APPLY_SCRIPT_HEADER = """#!/bin/bash
# Generated by Canary orchestrator — review before running
set -euo pipefail
REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
"""


def emit_node(state: PipelineState) -> dict:
    output_dir = Path(state.get("output_dir") or f"out/{state['service']}")
    output_dir.mkdir(parents=True, exist_ok=True)

    for rel_path, content in state["artifacts"].items():
        target = output_dir / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)

    # Write apply.sh that copies files from output_dir to repo
    apply_lines = [APPLY_SCRIPT_HEADER]
    for rel_path in state["artifacts"]:
        apply_lines.append(
            f'cp -v "$(dirname "$0")/{rel_path}" "$REPO_ROOT/{rel_path}"'
        )
    apply_script = output_dir / "apply.sh"
    apply_script.write_text("\n".join(apply_lines) + "\n")
    apply_script.chmod(0o755)

    return {"deploy_status": "emitted"}
