<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:include schemaLocation="EMailTypeCodeEnumerationV1.1.0.xsd"/>
	<xs:complexType name="EMailCommonData">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="PrimaryFlag" type="xs:boolean" use="optional" default="true">
					<xs:annotation>
						<xs:documentation>Indicates this is the primary email contact</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="TypeCode" type="EMailTypeCode" use="optional" default="Home"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>
