<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="IXREnumerationExtensionV1.1.0.xsd"/>
	<!-- 
		Facing Types 
	-->
	<xs:simpleType name="FacingTypeCode">
		<xs:union memberTypes="FacingTypeCodeEnumeration TypeCodeExtension"/>
	</xs:simpleType>
	<xs:simpleType name="FacingTypeCodeEnumeration">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="Left"/>
			<xs:enumeration value="Front"/>
			<xs:enumeration value="Top"/>
			<xs:enumeration value="Bottom"/>
			<xs:enumeration value="Right"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
