<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Richard L Halter (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="MeasurementCommonDataV1.3.0.xsd"/>
	<xs:include schemaLocation="PegCommonDataV1.0.0.xsd"/>
	<xs:complexType name="PegType">
		<xs:complexContent>
			<xs:extension base="PegCommonData">
				<xs:sequence>
					<xs:element name="HookID" type="xs:string"/>
					<xs:element name="HookLength" type="MeasurementCommonData"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
