<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Richard L Halter (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="URICommonDataV1.0.0.xsd"/>
	<xs:include schemaLocation="IXREnumerationExtensionV1.1.0.xsd"/>
	<xs:complexType name="URIType">
		<xs:simpleContent>
			<xs:extension base="URICommonData">
				<xs:attribute name="TypeCode" type="URITypeTypeCode"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="URITypeTypeCode">
		<xs:union memberTypes="URITypeTypeCodeEnumeration TypeCodeExtension"/>
	</xs:simpleType>
	<xs:simpleType name="URITypeTypeCodeEnumeration">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="Current"/>
			<xs:enumeration value="Historical"/>
			<xs:enumeration value="Future"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
