<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Richard L Halter (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="SequenceNumberCommonDataV1.0.0.xsd"/>
	<xs:complexType name="VertexCommonData">
		<xs:annotation>
			<xs:documentation>X,Y,Z location of a vertex </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="SequenceNumber" type="SequenceNumberType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>In case of multiple verticies, this defines the order in which they occur.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="X-Coordinate" minOccurs="0">
				<xs:annotation>
					<xs:documentation>coordinate whose value is determined by measuring parallel to an x-axis - Abscissa</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:decimal">
							<xs:attribute name="Accuracy" type="xs:int">
								<xs:annotation>
									<xs:documentation>Number of decimal digits</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Y-Coordinate" minOccurs="0">
				<xs:annotation>
					<xs:documentation>a coordinate whose value is determined by measuring parallel to a y-axis - ordinate</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:decimal">
							<xs:attribute name="Accuracy" type="xs:int">
								<xs:annotation>
									<xs:documentation>Number of decimal digits</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Z-Coordinate" minOccurs="0">
				<xs:annotation>
					<xs:documentation> a coordinate whose value is determined by measuring parallel to a z-axis </xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:decimal">
							<xs:attribute name="Accuracy" type="xs:int">
								<xs:annotation>
									<xs:documentation>number of decimal digits</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
